### ISSUE TITLE
Ngarla (ER 2842) should link to Yinhawangka

### ISSUE THREAD

**Issue by Taivo55** [cldf-datasets/phoible#10]
Presently Ngarla (ER 2842) links to "Ngarla on the Ashburton river south of the Hamersley range".  Ngarla (ISO 639-3 nlr) was retired in ISO 639-3 with varieties along the Ashburton river being assigned to Yinhawangka (Glottolog yinh1234, ISO 639-3 ywg).
https://glottolog.org/resource/languoid/id/ngar1286

**Comment by bambooforest** [comment]
@Taivo55 - thanks! fixed in:

https://github.com/phoible/dev/pull/262

**Comment by bambooforest** [comment]
@erichround -- FYI.
