### ISSUE TITLE
Picuris (UPSID 598) should be linked to Picuris Northern Tiwa

### ISSUE THREAD

**Issue by Taivo55** [cldf-datasets/phoible#12]
Picuris (UPSID 598) should link to Glottolog Picuris Northern Tiwa (picu1248) instead of Taos Northern Tiwa (nort1550).

I realize that you are currently in discussions to making better up-to-date links to Glottolog so I'm going to keep these suggestions to a minimum.  I appreciate your attention toward how to make these links better and keep them up-to-date

**Comment by bambooforest** [comment]
@Taivo55 -- no, please go ahead and make issues for any and all corrections. I'm happy to check these and make changes to the data in phoible dev, which we will use to release a new version of phoible data and its website in the future. At that time, we'll double-check that all the Glottocodes are valid to a particular Glottolog version for release.

**Comment by bambooforest** [comment]
>>> Picuris (UPSID 598) should link to Glottolog Picuris Northern Tiwa (picu1248) instead of Taos Northern Tiwa (nort1550).

@Taivo55 -- I'm sure you have a good reason, but can you clarify why picu1248 instead of nort1550?

There are two references:

* Hoijer, H. and Dozier, E.P. 1949. The phonemes of Tewa, Santa Clara dialect. International Journal of American Linguistics 15/3: 139-144.

* Trager, F.H. 1971. The phonology of Picuris. International Journal of American Linguistics 37: 29-33.

The former points to nort1550:

https://glottolog.org/resource/reference/id/136648

and here:

https://wals.info/languoid/lect/wals_code_twn

**Comment by Taivo55** [comment]
The Hoijer and Dozier (HD) reference is to a different, but (to quote HD in the article) more distantly related, language, Rio Grande Tewa (tewa1260).  I just checked the article itself and except for the one-sentence discussion of relationships in Tanoan in the introduction, Picuris is not mentioned again.  I looked at Glottolog and they do, indeed, link HD to Picuris, but they note that they pulled it automatically from the Phoible and WALS bibliographies, who both link HD to Picuris.  Both Phoible and WALS pulled their bibliographies from UPSID-2 (my term for the latest on-line version of UPSID).  But in Patterns of Sound (UPSID-1) there is no reference to HD at all and Picuris is linked solely (and correctly) to Trager 1971.  Sometime in the later history of UPSID, HD was added to Picuris incorrectly, I suspect by some over-zealous graduate assistant, because of the similarity of names in the Tanoan branches:  Tiwa, Tewa, Towa, (and Kiowa).  There is no difference between the Picuris inventories of UPSID-1 and UPSID-2.  In HD, however, the RG Tewa inventory lacks the voiceless aspirated series of stops along with other differences.  So the HD reference is spurious and has spread through the on-line databases from the UPSID-2 reference.

As far as whether to link to Picuris Northern Tiwa (picu1248) or Taos Northern Tiwa (nort1550), the name should say it all, but Felicia Trager (the author of Trager 1971) was married to George Trager, who wrote the first grammar sketch of Taos (G.L. Trager 1946).  George worked at Taos and Felicia worked at Picuris.  They kept their work separate and knew the difference between the languages (and the two pueblos).  I could provide some references if you need them.  I'm not sure when Glottolog separated Picuris and Taos from one another, but ISO 639-3 still links them in the same code (twf).  As I have mentioned before, I consider Glottolog to be more accurate in its linguistic assessments than ISO.

**Comment by Taivo55** [comment]
I might also note that in Merritt Ruhlen's _A Guide to the Languages of the World_ (1976, Stanford) he includes a Tewa (Santa Clara) phonological inventory referenced to HD separate from a Tiwa (Picuris) inventory referenced to Trager 1971.

**Comment by bambooforest** [comment]
Closed by https://github.com/phoible/dev/pull/264
