### ISSUE TITLE
Savara (PH 998) is a nonexistent language

### ISSUE THREAD

**Issue by Taivo55** [cldf-datasets/phoible#15]
Savara (PH 998) has been removed from both Glottolog and ISO 639-3 as a non-existent language

**Comment by bambooforest** [comment]
@drammock -- here's a new one. non-existent language:

https://iso639-3.sil.org/sites/iso639-3/files/change_requests/2015/2015-010.pdf

i suppose we should remove it from the raw data, but what should we do about the InventoryID?

**Comment by drammock** [comment]
I think the right conclusion here is (as mentioned at the bottom of page 2 of the SIL change request) that Savara is an alternate name for Sora (an austroasiatic lx, not dravidian).  It is listed as an alternate name for Sora [here](http://www.ling.hawaii.edu/austroasiatic/), [here](https://en.wikipedia.org/wiki/Sora_language), and as an alternate name for the Sora peoples [here](https://en.wikipedia.org/wiki/Sora_people), in addition to the P.C. cited in the SIL change request.  Looking at the inventories for `sora1254` and sava1244` they are similar enough to plausibly be different analyses of the same lect (or two closely related lects):

```R
phoible %>% 
    filter(InventoryID == 998 | LanguageName == "Sora") %>%
    select(InventoryID, Phoneme) %>%
    group_split(InventoryID) %>%
    lapply(function(tib) pull(tib, Phoneme))
```
result is this:

```
[[1]]
 [1] "b" "b̻" "d̪" "d̻" "j" "k" "k̻" "l" "m" "n̪" "p" "p̻" "r" "s" "t̪" "ŋ" "ɡ" "ɲ" "ɾ" "e" "i" "o" "u" "æ" "ɑ" "ə" "ɛ" "ɪ" "ʊ" "ʌ"

[[2]]
 [1] "b" "c" "d" "j" "k" "l" "m" "n" "p" "r" "s" "t" "ŋ" "ɟ" "ɡ" "ɲ" "ɽ" "ʔ" "a" "e" "i" "o" "u" "ə" "ɨ" "ʊ"
```

So I'd be inclined to keep the inventory and its InventoryID, and change the isocode and glottocode with which we associate it.

**Comment by bambooforest** [comment]
@drammock -- thanks!

**Comment by Taivo55** [comment]
Good call

**Comment by drammock** [comment]
@bambooforest can you send me the `anonymous1927.pdf` from which this inventory was extracted, so I can double-check that my proposal is not contradicted by anything the author says?
