### ISSUE TITLE
Shanenawa (SAPHON 2013) should be linked to Yawanawa

### ISSUE THREAD

**Issue by Taivo55** [cldf-datasets/phoible#18]
Shanenawa (SAPHON 2013) should be linked to Glottolog Yawanawa (yawa1260) instead of to Shall-Zwall (shal1238)

**Comment by bambooforest** [comment]
@Taivo55 -- here:

https://github.com/phoible/dev/issues/245

we updated this to:

https://glottolog.org/resource/languoid/id/shan1283

given the same language name, but here:

http://linguistics.berkeley.edu/~saphon/en/inv/Shanenawa.html

the note say:

"This language is considered a variety of Yawanawa (ywn) by ISO 639."

Could you please confirm? I'm unable to access the dissertation here:

http://repositorio.unicamp.br/bitstream/REPOSIP/270395/1/Candido_GlauciaVieira_D.pdf

**Comment by Taivo55** [comment]
[Shanenawa.pdf](https://github.com/cldf-datasets/phoible/files/4701514/Shanenawa.pdf)

ISO created a new code for Shanenawa
https://iso639-3.sil.org/code/swo

When I posted my original request, I must not have noted the existence of shan1283 or else I would have made the link to that.  My main goal originally was to move the link out of Africa into South America.  I think that it should link to Shanenawa shan1283 as you noticed.  Shanenawa as a separate language is supported by both Glottolog and ISO

**Comment by bambooforest** [comment]
@Taivo55 -- excellent, we moved it and a few other data points out of Africa some time back. I will update to `shan1283`.

**Comment by bambooforest** [comment]
Closed by https://github.com/phoible/dev/pull/264
