### ISSUE TITLE
Shilha (SPA 123) should be linked to Tachelhit

### ISSUE THREAD

**Issue by Taivo55** [cldf-datasets/phoible#19]
Shilha (SPA 123) should be linked to Glottlog Tachelhit (tach1250) instead of to Tarifiyt-Beni-Iznasen-Eastern Middle Atlas Berber (tari1263).  Applegate (1958) is listed as a source in Glottolog for both Tachelhit and Tarifiyt..., but I have a copy of Applegate (1958) and his informant was unmistakably from the Tachelhit region of Morocco.  There wasn't any ambiguity to Applegate.

**Comment by bambooforest** [comment]
Thanks @Taivo55 

FYI @d97hah

**Comment by bambooforest** [comment]
This makes sense because it's also listed as such in UPSID 542.

Updated.
