### ISSUE TITLE
Soutern should be Southern

### ISSUE THREAD

**Issue by Taivo55** [cldf-datasets/phoible#21]
There are three entries that have misspelled "Southern" as "Soutern":
Soutern Tai (Ko Samui) (EA 2333)
Soutern Tai (Nakhon Si Thammarat) (EA 2573)
Soutern Tai (Surat) (EA 2472))
I checked and these are misspelled in the source material.  While it is almost always preferable to preserve the spelling of the source ("Tai" for "Thai", for example), when the misspelling is of a common English word that is not replicated anywhere else and isn't part of a widespread "error" in many sources (in which case it isn't an error at all), I would suggest that a simple correction to "southern" is in order.  Glottolog has Southern Thai (sout2746).

**Comment by bambooforest** [comment]
Thanks @Taivo55 

FYI @macleginn

**Comment by Taivo55** [comment]
Nice to meet you, Dmitry.  I have, of course, encountered your name throughout Phoible.  I am John McLaughlin, Associate Professor of English at Utah State University, Logan, Utah.  PhD, Linguistics, University of Kansas.  (I am the McLaughlin of McLaughlin 1987 here at Panamint (PH 1133)).
