### ISSUE TITLE
Tajik (Bukhara) (EA 2266) and Bukharan Tajik (UZ 2219) should both link to Tajik

### ISSUE THREAD

**Issue by Taivo55** [cldf-datasets/phoible#22]
Tajik (Bukhara) (EA 2266) should link to Glottolog Bukharic (bukh1238) instead of to Tajik (taji1245).  The reference links to an IPA sketch of Bukharan Tajik.  SEE COMMENT BELOW

**Comment by Taivo55** [comment]
Bukharan Tajik (UZ 2219) also uses the same IPA sketch of Bukhara Tajik as this one and links to Bukharic.  But it looks like there is a confusion between Bukharic and Tajik (not just here but elsewhere, such as in the Glottlog references).  Bukharic is the Judeo-Tajik language and Tajik is everything else.  Thus both of the Phoible entries (2266 and 2219) should be Tajik and neither Bukharic.

**Comment by bambooforest** [comment]
@Taivo55 -- good catch. Thanks!
