### ISSUE TITLE
Map label errors

### ISSUE THREAD

**Issue by majtotim** [cldf-datasets/phoible#3]
Here are some errors on the interactive map: 1) Acehnese is mispelled; 2) The location marker for Minangkabau should be located in West Sumatra, not Aceh province.

**Comment by xrotwang** [comment]
@d97hah this comment also applies to https://glottolog.org/resource/languoid/id/mina1268

**Comment by d97hah** [comment]
Thx fixed for next version!

Pada tanggal Sel, 4 Jun 2019 pukul 19.41 Robert Forkel <
notifications@github.com> menulis:

**Comment by bambooforest** [comment]
These are fixed in Glottolog and in PHOIBLE dev and will be updated in the next release of PHOIBLE CLDF data and PHOIBLE online.
