### ISSUE TITLE
matching between tables

### ISSUE THREAD

**Issue by HedvigS** [cldf-datasets/phoible#39]
In order to match entires in inventories.csv to glottocodes, am I meant to use the "Name" column in languages.csv?

**Comment by xrotwang** [comment]
No, you'd join [ValueTable](https://github.com/cldf-datasets/phoible/tree/master/cldf#table-valuescsv), and `LanguageTable` via the `Language_ID` in `ValueTable`.

**Comment by HedvigS** [comment]
Okay. So how should I act with the inventories table?

**Comment by HedvigS** [comment]
Aaah I use the Inventory_ID in the values table??
