### ISSUE TITLE
Sesotho inventory (Bantu) marked as Sissano (Austronesian)

### ISSUE THREAD

**Issue by martsen79** [cldf-datasets/phoible#4]
The inventory here:

https://phoible.org/inventories/view/1017

is Sesotho but marked as Sissano.

**Comment by bambooforest** [comment]
@martsen79 - thanks for pointing this out. This issue was fixed in the development version of phoible:

https://github.com/phoible/dev/issues/221

and will be updated next time we dump a CLDF release.
