### ISSUE TITLE
Language Label Error

### ISSUE THREAD

**Issue by Taivo55** [cldf-datasets/phoible#5]
Your entry Lule (SAPHON 1930) is incorrectly associated with Glottolog language Olu'bo (olub1238).  It should be associated with Glottolog language Lule (lule1238).

**Comment by bambooforest** [comment]
@Taivo55 -- thanks for pointing this out. We have fixed this in the development version of phoible:

https://github.com/phoible/dev/issues/245

and when we release a new version of the CLDF data and upload it to the website, this will be corrected.

FYI @drammock, @xrotwang
