### ISSUE TITLE
Another Language Label Error

### ISSUE THREAD

**Issue by Taivo55** [cldf-datasets/phoible#6]
Ma"di' (PH 932) incorrectly links to Glottolog Madi (Papua New Guinea) (madi1261).  It actually should link to Glottolog Ma'di (madi 1260).  The reference cited for the Phoible entry is of the African Ma'di language, not the New Guinea language.
https://www.degruyter.com/view/title/16629?language=en

**Comment by bambooforest** [comment]
@Taivo55 -- thanks for pointing out this mistake in Glottocode assignment.

I have updated it here:

https://github.com/phoible/dev/pull/258

and when we release the next version of phoible CLDF and phoible online, it will be update there as well.
