### ISSUE TITLE
Mbe' should be Mbe

### ISSUE THREAD

**Issue by Taivo55** [cldf-datasets/phoible#7]
The inventory Mbe (GM 1599) is incorrectly linked to Glottolog Mbe' (mbee1250).  It should be linked to Glottolog Mbe (mbee1249).  The reference given for Mbe (GM 1599) is a manuscript for the Mbe language of Cross River State in Nigeria.  The Mbe' language is spoken in Cameroon, not Nigeria.

**Comment by bambooforest** [comment]
Thank you again @Taivo55 -- I've updated the Glottocode here:

https://github.com/phoible/dev/pull/260

And for the next version release, the data will be updated here, in Zenodo, and on the website.
